server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  application:
    name: student
  datasource:
    url: jdbc:postgresql://localhost:5432/studentdata
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
